version: 2.1
jobs:
  first Job:
  commands:
    greeting:
      parameters:
        myparam:
          default: "First Parameter check"
          type: string
    steps:
      - run: echo "hello <<parameters.myparam>>"