version: 2.1
jobs:
  Hello World Job:
    docker:
      - image: ubuntu
    steps:
      - run: echo "Helloooooooooooooooo" > mybook.txt
      - run: cat mybook.txt
      - run: ls

workflows:
  FunnyFlow:
    jobs:
      - Hello World Job
  